// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtCGX0I8sO5MmYL9Rlyv6OfWSr5sKrI3g',
    appId: '1:1070512925455:web:1751f47a0a9ffa7f84ec7a',
    messagingSenderId: '1070512925455',
    projectId: 'storagio-ce383',
    authDomain: 'storagio-ce383.firebaseapp.com',
    storageBucket: 'storagio-ce383.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMq-OhibiXrgBmTV-bbf5lDCpj02U9gLc',
    appId: '1:1070512925455:android:628c887f78b9a6c484ec7a',
    messagingSenderId: '1070512925455',
    projectId: 'storagio-ce383',
    storageBucket: 'storagio-ce383.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoYE4JavyuJAzddW1KimXg6JAWDA8Is1s',
    appId: '1:1070512925455:ios:413279825652e56184ec7a',
    messagingSenderId: '1070512925455',
    projectId: 'storagio-ce383',
    storageBucket: 'storagio-ce383.firebasestorage.app',
    iosBundleId: 'com.example.storagio',
  );
}
